//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovacionDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMunicipio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatMunicipio()
        {
            this.Instituciones = new HashSet<Instituciones>();
        }
    
        public int idMunicipio { get; set; }
        public string strDescripcion { get; set; }
        public Nullable<int> idCatEstado { get; set; }
    
        public virtual CatEstado CatEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instituciones> Instituciones { get; set; }
    }
}
