//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovacionDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatTrimestre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatTrimestre()
        {
            this.Encuadre = new HashSet<Encuadre>();
            this.TrimestreTema = new HashSet<TrimestreTema>();
        }
    
        public int idTrimestre { get; set; }
        public string strDescripcion { get; set; }
        public Nullable<System.DateTime> strInicio { get; set; }
        public Nullable<System.DateTime> strFin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encuadre> Encuadre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrimestreTema> TrimestreTema { get; set; }
    }
}
