//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovacionDocentes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class innovaciontibdEntities : DbContext
    {
        public innovaciontibdEntities()
            : base("name=innovaciontibdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Aprendizaje> Aprendizaje { get; set; }
        public virtual DbSet<CatAsignatura> CatAsignatura { get; set; }
        public virtual DbSet<CatEstado> CatEstado { get; set; }
        public virtual DbSet<CatEstadoRegistro> CatEstadoRegistro { get; set; }
        public virtual DbSet<CatGrado> CatGrado { get; set; }
        public virtual DbSet<CatInstrumentosEvaluacion> CatInstrumentosEvaluacion { get; set; }
        public virtual DbSet<CatJerarquizacion> CatJerarquizacion { get; set; }
        public virtual DbSet<CatMunicipio> CatMunicipio { get; set; }
        public virtual DbSet<CatNivel> CatNivel { get; set; }
        public virtual DbSet<CatPuesto> CatPuesto { get; set; }
        public virtual DbSet<CatTipoCompetencia> CatTipoCompetencia { get; set; }
        public virtual DbSet<CatTrimestre> CatTrimestre { get; set; }
        public virtual DbSet<Contenido> Contenido { get; set; }
        public virtual DbSet<Dosificacion> Dosificacion { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Encuadre> Encuadre { get; set; }
        public virtual DbSet<Instituciones> Instituciones { get; set; }
        public virtual DbSet<Proposito> Proposito { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tema> Tema { get; set; }
        public virtual DbSet<TrimestreTema> TrimestreTema { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
