//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovacionDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Encuadre = new HashSet<Encuadre>();
            this.Usuario = new HashSet<Usuario>();
            this.CatAsignatura = new HashSet<CatAsignatura>();
        }
    
        public int idEmpleado { get; set; }
        public string strNombre { get; set; }
        public string strAPaterno { get; set; }
        public string strAMaterno { get; set; }
        public int idNivel { get; set; }
        public string strRFC { get; set; }
        public string strCurp { get; set; }
        public System.DateTime strFechaNacimiento { get; set; }
        public int idPuesto { get; set; }
        public int idInstitucion { get; set; }
        public int idCatEstadoR { get; set; }
    
        public virtual CatEstadoRegistro CatEstadoRegistro { get; set; }
        public virtual CatNivel CatNivel { get; set; }
        public virtual CatPuesto CatPuesto { get; set; }
        public virtual Instituciones Instituciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encuadre> Encuadre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatAsignatura> CatAsignatura { get; set; }
    }
}
