//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovacionDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuadre
    {
        public int idEncuadre { get; set; }
        public Nullable<System.DateTime> dteFechaInicio { get; set; }
        public Nullable<System.DateTime> dteFechaFin { get; set; }
        public Nullable<int> idAsignatura { get; set; }
        public Nullable<int> idCatGrado { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<int> idTrimestre { get; set; }
        public string strDuracion { get; set; }
        public Nullable<int> idTema { get; set; }
        public Nullable<int> idContenido { get; set; }
        public Nullable<int> idProposito { get; set; }
        public Nullable<int> idEvaluacion { get; set; }
        public Nullable<int> idAprendizaje { get; set; }
        public string strInicio { get; set; }
        public string strDesarollo { get; set; }
        public string strFin { get; set; }
        public string strObservacion { get; set; }
    
        public virtual CatAsignatura CatAsignatura { get; set; }
        public virtual CatGrado CatGrado { get; set; }
        public virtual CatTrimestre CatTrimestre { get; set; }
        public virtual Contenido Contenido { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Proposito Proposito { get; set; }
        public virtual Tema Tema { get; set; }
    }
}
