//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovacionDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proposito()
        {
            this.Encuadre = new HashSet<Encuadre>();
        }
    
        public int idProposito { get; set; }
        public string strDescripcion { get; set; }
        public int idTema { get; set; }
        public int idCatTipoCompetencia { get; set; }
    
        public virtual CatTipoCompetencia CatTipoCompetencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encuadre> Encuadre { get; set; }
        public virtual Tema Tema { get; set; }
    }
}
