//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovacionDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tema()
        {
            this.Contenido = new HashSet<Contenido>();
            this.Encuadre = new HashSet<Encuadre>();
            this.Proposito = new HashSet<Proposito>();
            this.CatInstrumentosEvaluacion = new HashSet<CatInstrumentosEvaluacion>();
        }
    
        public int idTema { get; set; }
        public string strNombre { get; set; }
        public string strDescripcion { get; set; }
        public int idCatJeraquizacion { get; set; }
        public int idDosificacion { get; set; }
        public int idAprendizaje { get; set; }
    
        public virtual Aprendizaje Aprendizaje { get; set; }
        public virtual CatJerarquizacion CatJerarquizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contenido> Contenido { get; set; }
        public virtual Dosificacion Dosificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encuadre> Encuadre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposito> Proposito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatInstrumentosEvaluacion> CatInstrumentosEvaluacion { get; set; }
    }
}
