//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovacionDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idUsuario { get; set; }
        public string strNickName { get; set; }
        public string straMail { get; set; }
        public string strPassword { get; set; }
        public int idEmpleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public bool Succeeded { get; internal set; }
    }
}
